seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  #checkpoint_path: "/proj/tsarisa/tmp/100_million_91variables"
  checkpoint_path: "/lustre/orion/stf218/world-shared/atsaris/tmp/tmp_checkpoints"  
  checkpoint_filename: "multi_last"

  resume_from_checkpoint: False
  #resume_from_checkpoint: "${trainer.default_root_dir}/checkpoints/last.ckpt"

# ---------------------------- PARALLELISM -------------------------------------
parallelism:
  cpu_offloading: False
# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.00002
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_steps: 1000
  max_steps: 20000
  warmup_start_lr: 1e-8
  eta_min: 1e-8

  net:
    class_path: climax.arch.ClimaX
    init_args:
      default_vars: [
        "2m_temperature",
        "10m_u_component_of_wind",
        "10m_v_component_of_wind",
        "geopotential_50",
        "geopotential_70",
        "geopotential_100",
        "geopotential_150",
        "geopotential_200",
        "geopotential_250",
        "geopotential_300",
        "geopotential_400",
        "geopotential_500",
        "geopotential_600",
        "geopotential_700",
        "geopotential_850",
        "geopotential_925",
        "geopotential_1000",
        "specific_humidity_10",
        "specific_humidity_20",
        "specific_humidity_30",
        "specific_humidity_50",
        "specific_humidity_70",
        "specific_humidity_100",
        "specific_humidity_150",
        "specific_humidity_200",
        "specific_humidity_250",
        "specific_humidity_300",
        "specific_humidity_400",
        "specific_humidity_500",
        "specific_humidity_600",
        "specific_humidity_700",
        "specific_humidity_850",
        "specific_humidity_925",
        "specific_humidity_1000",
        "temperature_10",
        "temperature_20",
        "temperature_30",
        "temperature_50",
        "temperature_70",
        "temperature_100",
        "temperature_150",
        "temperature_200",
        "temperature_250",
        "temperature_300",
        "temperature_400",
        "temperature_500",
        "temperature_600",
        "temperature_700",
        "temperature_850",
        "temperature_925",
        "temperature_1000",
        "u_component_of_wind_10",
        "u_component_of_wind_20",
        "u_component_of_wind_30",
        "u_component_of_wind_50",
        "u_component_of_wind_70",
        "u_component_of_wind_100",
        "u_component_of_wind_150",
        "u_component_of_wind_200",
        "u_component_of_wind_250",
        "u_component_of_wind_300",
        "u_component_of_wind_400",
        "u_component_of_wind_500",
        "u_component_of_wind_600",
        "u_component_of_wind_700",
        "u_component_of_wind_850",
        "u_component_of_wind_925",
        "u_component_of_wind_1000",
        "v_component_of_wind_10",
        "v_component_of_wind_20",
        "v_component_of_wind_30",
        "v_component_of_wind_50",
        "v_component_of_wind_70",
        "v_component_of_wind_100",
        "v_component_of_wind_150",
        "v_component_of_wind_200",
        "v_component_of_wind_250",
        "v_component_of_wind_300",
        "v_component_of_wind_400",
        "v_component_of_wind_500",
        "v_component_of_wind_600",
        "v_component_of_wind_700",
        "v_component_of_wind_850",
        "v_component_of_wind_925",
        "v_component_of_wind_1000",
      ]
      patch_size: 4
      decoder_depth: 2
      mlp_ratio: 4
      drop_path: 0.1
      drop_rate: 0.1
      aggregated_variables: 1

# ---------------------------- DATA -------------------------------------------
data:
  dict_root_dirs: {
    #'mpi-esm': '/proj/tsarisa/cp_from_home/data/5.625_deg', # 100
    'mpi-esm': '/lustre/orion/stf218/scratch/atsaris/code/tmp25/climaxSC24_end2end/DATA_tmp_5.0', # 100    
  }
  dict_start_idx: {
    'mpi-esm': 0,
  }
  dict_end_idx: {
    'mpi-esm': 1,
  }
  dict_in_variables: {
    'mpi-esm': [
      "2m_temperature",
      "10m_u_component_of_wind",
      "10m_v_component_of_wind",
      "geopotential_50",
      "geopotential_100",
      "geopotential_150",
      "geopotential_200",
      "geopotential_250",
      "geopotential_300",
      "geopotential_400",
      "geopotential_500",
      "geopotential_600",
      "geopotential_700",
      "geopotential_850",
      "geopotential_925",
      "geopotential_1000",
      "specific_humidity_10",
      "specific_humidity_20",
      "specific_humidity_30",
      "specific_humidity_50",
      "specific_humidity_70",
      "specific_humidity_100",
      "specific_humidity_150",
      "specific_humidity_200",
      "specific_humidity_250",
      "specific_humidity_300",
      "specific_humidity_400",
      "specific_humidity_500",
      "specific_humidity_600",
      "specific_humidity_700",
      "specific_humidity_850",
      "specific_humidity_925",
      "specific_humidity_1000",
      "temperature_10",
      "temperature_20",
      "temperature_30",
      "temperature_50",
      "temperature_70",
      "temperature_100",
      "temperature_150",
      "temperature_200",
      "temperature_250",
      "temperature_300",
      "temperature_400",
      "temperature_500",
      "temperature_600",
      "temperature_700",
      "temperature_850",
      "temperature_925",
      "temperature_1000",
      "u_component_of_wind_10",
      "u_component_of_wind_20",
      "u_component_of_wind_30",
      "u_component_of_wind_50",
      "u_component_of_wind_70",
      "u_component_of_wind_100",
      "u_component_of_wind_150",
      "u_component_of_wind_200",
      "u_component_of_wind_250",
      "u_component_of_wind_300",
      "u_component_of_wind_400",
      "u_component_of_wind_500",
      "u_component_of_wind_600",
      "u_component_of_wind_700",
      "u_component_of_wind_850",
      "u_component_of_wind_925",
      "u_component_of_wind_1000",
      "v_component_of_wind_10",
      "v_component_of_wind_20",
      "v_component_of_wind_30",
      "v_component_of_wind_50",
      "v_component_of_wind_70",
      "v_component_of_wind_100",
      "v_component_of_wind_150",
      "v_component_of_wind_200",
      "v_component_of_wind_250",
      "v_component_of_wind_300",
      "v_component_of_wind_400",
      "v_component_of_wind_500",
      "v_component_of_wind_600",
      "v_component_of_wind_700",
      "v_component_of_wind_850",
      "v_component_of_wind_925",
      "v_component_of_wind_1000",
    ],
  }
  dict_out_variables: {
    'mpi-esm': ["geopotential_500", "temperature_850", "2m_temperature", "10m_u_component_of_wind", "10m_v_component_of_wind"],
  }
  dict_max_predict_ranges: {
    'mpi-esm': 720,
  }
  dict_random_lead_time: {
    'mpi-esm': True,
  }
  dict_hrs_each_step: {
    'mpi-esm': 1,
  }
  dict_buffer_sizes: {
    'mpi-esm': 1, #100,
  }
  num_workers: 1
  pin_memory: False
